spring:
  h2:
    console:
      path: /console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password:
    url: jdbc:h2:mem:DB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081
